### ISSUE TITLE
Several inhibitors smiles have unspecified stereochemistry

### ISSUE THREAD

**Issue by ChayaSt** [choderalab/PDBfinder#11]
I'm using [`clinical-kinase-inhibitors.csv`](https://github.com/choderalab/PDBfinder/blob/master/approved/clinical-kinase-inhibitors.csv) to generate  `OEMol`. I get this error when trying to parse Midostaurin and Neratinib smiles:

```
Warning: ~{N}-[4-[3-chloro-4-(2-pyridylmethoxy)anilino]-3-cyano-7-ethoxy-6-quinolyl]-4-(dimethylamino)but-2-enamide failed due to unspecified stereochemistry with strict stereo enabled
Traceback (most recent call last):
  File "fragment_kinase_inhibitors.py", line 13, in <module>
    charged = get_charges(mol, keep_confs=1)
  File "/Users/chayastern/anaconda/lib/python3.6/site-packages/openmoltools/openeye.py", line 67, in get_charges
    charged_copy = generate_conformers(molecule, max_confs=max_confs, strictStereo=strictStereo)  # Generate up to max_confs conformers
  File "/Users/chayastern/anaconda/lib/python3.6/site-packages/openmoltools/openeye.py", line 250, in generate_conformers
    raise(RuntimeError("omega returned error code %d" % status))
RuntimeError: omega returned error code 0
```
When I use the smiles string provided by [drug bank](https://www.drugbank.ca/drugs/DB06595) it works. Should I change the smiles string in `clinical-kinase-inhibitors.csv` to include stereochemistry?

**Comment by steven-albanese** [comment]
Sure! I don't actually use the SMILES strings in there at the moment, so feel free to convert them to the format that works for you
